### ISSUE TITLE
Convert from Tech to Source Handler

### ISSUE THREAD

**Issue by heff** [videojs/videojs-contrib-hls#193]
The source handler interface has now been merged into core video.js (videojs/video.js#1560) so we could start working toward moving this over towards that interface.

Dependencies: 
- [x] #170 Combine the flash tech and HLS tech's currentTime methods
- [x] #131 Remove Buffer Management from Player API Methods
- [ ] #175 Seeking event never fires 
- [x] videojs/videojs-contrib-media-sources#18 Implement a duration method

After the dependencies are finished, there's pseudo code for HLS in videojs/video.js#1560

**Comment by forbesjo** [comment]
This is very done
